# Configure Netlify to serve particular headers for certain routes
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Referrer-Policy = "strict-origin"
    Strict-Transport-Security = "max-age=31557600; includeSubDomains"
    X-Content-Type = "nosniff"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    # Multi-key header rules are expressed with multi-line strings.
    Content-Security-Policy = '''
    default-src 'none';
    base-uri: 'none';
    form-action 'none';
    frame-ancestors 'none';
    img-src 'self';
    connect-src 'self' https://p.trellocdn.com;
    script-src 'self' https://p.trellocdn.com https://gist.github.com;
    style-src 'self' https://p.trellocdn.com https://github.githubassets.com;
    '''
